---
- name: Backup Application Data
  hosts: webservers
  become: yes

  vars:
    backup_dir: /tmp/backup
    s3_bucket: cloud-native-devops-backups-dev-607327612004

  tasks:
    - name: Create backup directory
      file:
        path: "{{ backup_dir }}"
        state: directory

    - name: Backup Docker volumes
      command: docker run --rm -v app_data:/data -v {{ backup_dir }}:/backup alpine tar czf /backup/app-data-{{ ansible_date_time.date }}.tar.gz /data
      ignore_errors: yes

    - name: Backup Prometheus data
      archive:
        path: /opt/monitoring/prometheus/data
        dest: "{{ backup_dir }}/prometheus-data-{{ ansible_date_time.date }}.tar.gz"

    - name: Upload to S3
      command: aws s3 cp {{ backup_dir }}/ s3://{{ s3_bucket }}/backups/{{ ansible_date_time.date }}/ --recursive

    - name: Clean up local backups
      file:
        path: "{{ backup_dir }}"
        state: absent
